services:
  neo4j:
    image: neo4j:5.26
    ports:
      - "7475:7474"  # HTTP
      - "7688:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc-extended"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
    networks:
      - app_network
    container_name: neo4j_db
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/workspace:cached
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - app_network
    environment:
      - NEO4J_URI=bolt://neo4j_db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
    command: sleep infinity
    container_name: app_dev

networks:
  app_network:
    name: neo4j_dev_network
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
