services:
  neo4j:
    build:
      context: .
      dockerfile: Docker/neo4j/Dockerfile
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - graph_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]

  app:
    build:
      context: .
      dockerfile: Docker/app/Dockerfile
    volumes:
      - ./src:/workspace/src
      - .:/workspace
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - graph_net
    environment:
      - NEO4J_URI=bolt://neo4j:7687

networks:
  graph_net:

volumes:
  neo4j_data: